### ISSUE TITLE
Please update stable version and upload to PyPI

### ISSUE THREAD

**Issue by davidfokkema** [uvemas/ViTables#24] opened 2013-11-25 14:31 UTC
The stable version of ViTables does not work on a Mac. That particular bug has been fixed sometime in 2011. There has been a lot of work since that time. Also, if this package is uploaded to PyPI, I can tell my coworkers to do a simple

```
$ pip install vitables
```

to install an awesome tool for inspecting our data files. Thanks for your work!

**Comment by QuLogic** [comment] 2015-11-16 06:00
So is there any idea when a new release might be generated? Python 3 support is there in the develop branch, and it'd be great to get that into Fedora since they're moving to Python 3-only by default.

**Comment by equaeghe** [comment] 2016-11-24 10:11
Perhaps making a new release should be separated from uploading to PyPI. Next to Python 3 support becoming more important, there's also the Qt4-to-Qt5 transition.

**Comment by uvemas** [comment] 2017-06-02 15:21
I have prepared source and wheel packages of the 3.0.0 release but I cannot upload them to PyPI. The reason seems to be that @alexey-naydenov uploaded an older release in the past and now I have no permission to upload the new packages. Please, @alexey-naydenov contact me in order to fix this problem. Thanks.

**Comment by benjello** [comment] 2018-04-30 11:11
The problem is still pending ...

**Comment by noraj** [comment] 2018-08-08 21:18
https://pypi.org/project/ViTables/#history

there is only version 2.2a1 pre-release on pypi

also this version can't be installed

 ```
$ sudo pip2 install ViTables     
Collecting ViTables
  Using cached https://files.pythonhosted.org/packages/fc/45/32ea0cc9ab1e431605f5bc2a2fde344c682c82d4db9911b117013121a922/ViTables-2.2a1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-RNkjMZ/ViTables/setup.py", line 31, in <module>
        version=read('VERSION'),
      File "/tmp/pip-install-RNkjMZ/ViTables/setup.py", line 28, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    IOError: [Errno 2] No such file or directory: '/tmp/pip-install-RNkjMZ/ViTables/VERSION'

$ sudo pip install ViTables
Collecting ViTables
  Using cached https://files.pythonhosted.org/packages/fc/45/32ea0cc9ab1e431605f5bc2a2fde344c682c82d4db9911b117013121a922/ViTables-2.2a1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8v6q9y9r/ViTables/setup.py", line 31, in <module>
        version=read('VERSION'),
      File "/tmp/pip-install-8v6q9y9r/ViTables/setup.py", line 28, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-8v6q9y9r/ViTables/VERSION'
```

**Comment by ankostis** [comment] 2018-12-13 09:48
@alexey-naydenov seems to be active lately - maybe @uvemas you want to contact him again, and fix the permissions problem with PyPi.

**Comment by uvemas** [comment] 2018-12-13 17:21
Thanks @ankostis for let me know about it. I'll try to contact him ASAP.

**Comment by uvemas** [comment] 2018-12-14 14:51
Hi @alexey-naydenov. Thanks for coming back. I've just checked my PyPI account. Please transfer ownership of project to me (username is vmas).

**Comment by alexey-naydenov** [comment] 2018-12-14 15:19
Added you (vmas) as owner. It does not seem I can remove myself from the project, feel free to do so if you have such option. In any case you can now delete pypi project and recreate it.

**Comment by uvemas** [comment] 2018-12-14 17:55
OK. I've just removed you from the project. Thanks again for your help.

**Comment by uvemas** [comment] 2018-12-21 20:39
I've uploaded ViTables 3.0.0 to PyPI and checked that it installs fine in a virtual environment on Windows 10 and Ubuntu.

**Closed as completed** 2018-12-24 11:29 UTC
