### ISSUE TITLE
Timeseries broken for Python2.7 installs

### ISSUE THREAD

**Issue by marfel** [uvemas/ViTables#77] opened 2017-07-25 14:05 UTC
Hi, it seems to me the `time_series` plugin has issues with the Python2.7 `ConfigParser`. The plugin throws an error unless I do this:

```diff
diff --git a/vitables/plugins/timeseries/time_series.py b/vitables/plugins/timeseries/time_series.py
index f4edbf0..9e258b5 100644
--- a/vitables/plugins/timeseries/time_series.py
+++ b/vitables/plugins/timeseries/time_series.py
@@ -161,12 +161,12 @@ def datetimeFormat():
     """The format string to be used when rendering the time series.
     """
 
-    config = configparser.ConfigParser(interpolation=None)
+    config = configparser.ConfigParser()
     ini_filename = os.path.join(os.path.dirname(__file__), 'time_format.ini')
     def_dtformat = '%c'
     try:
-        config.read_file(open(ini_filename))
-        datetime_format = config['Timeseries']['strftime']
+        config.read([ini_filename])
+        datetime_format = config.get('Timeseries', 'strftime')
     except (IOError, configparser.ParsingError):
         datetime_format = def_dtformat
```

**Comment by uvemas** [comment] 2017-07-26 09:04
Hi. Thanks for the report. I wasn't aware of this issue. I suppose the problems are caused by the changes in the configparser module introduced in Python3. I'll have a look ASAP and let you know if I find a better solution.

Thanks again.

**Comment by mivade** [comment] 2017-09-06 15:23
The easiest fix here is to require on the [backported](https://pypi.python.org/pypi/configparser/3.5.0) `configparser` module for Python 2.7.

**Comment by uvemas** [comment] 2019-12-27 21:36
Closing this issue as Python-2.7 is currently not supported.

**Closed by uvemas** 2019-12-27 21:36 UTC
