### ISSUE TITLE
PyQt5 requirements obsolete?

### ISSUE THREAD

**Issue by marfel** [uvemas/ViTables#76] opened 2017-07-23 10:00 UTC
Hi,
when I install and run `vitables` on a relatively clean Ubuntu 16.04/Python2.7 server using conda, I get

```
pkg_resources.DistributionNotFound: The 'PyQt5>=5.5.1' distribution was 
not found and is required by ViTables
```

However, `conda search pyqt` yields 

```
pyqt                         4.11.4                   py27_0  conda-forge     
                             4.11.4                   py34_0  conda-forge     
...
                          *  5.6.0                    py27_2  defaults        
...
```

I am no expert in setuptools, conda, Qt and other such higher magic. But if I simply remove the line `PyQt5 (>=5.5.1)` from

```
<conda-env>/lib/python2.7/site-packages/ViTables-3.0.0-py2.7.egg-info/requires.txt
```
the program runs flawlessly. Is this the intented behaviour?

**Comment by uvemas** [comment] 2017-07-23 19:50
No, it is not intended behavior. It is a compatibility problem mentioned in the [last entry of the ViTables FAQ](http://vitables.org/Docs/faq.html#can-i-use-vitables-with-anaconda3). I'll try to get it fixed in the next release. Thanks for your report.

**Comment by marfel** [comment] 2017-07-24 07:30
Ah, sorry, I overlooked the FAQ entry (we are using miniconda, not the full Anaconda suite). But since you already have this on the radar, feel free to close this issue.

**Comment by uvemas** [comment] 2017-07-24 15:42
No problem. Thanks for the report.

**Closed by uvemas** 2017-07-24 15:42 UTC
